# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: streakode
    main: .
    binary: streakode
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitSHA={{.Commit}}
      - -X main.BuildTime={{.Date}}
    archive:
      format: tar.gz
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

  - id: streakode-windows
    main: .
    binary: streakode
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitSHA={{.Commit}}
      - -X main.BuildTime={{.Date}}
    archive:
      format: zip
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

archives:
  # General configuration for archives
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - 'Merge pull request'
      - 'Merge branch'
